// to run: start a powershell command line on root folder of this file, and then:
// node scrape_highlights.js

var fs = require('fs');
var json2csv = require('json2csv').Parser;
var request = require('request');
var cheerio = require('cheerio');
const chalk = require('chalk');
const utf8 = require('utf8');

sitelist = [ // COPY LIST OF URLS HERE
    //"https://www.mcdonalds.pt/ementa/produtos/mcveggie/","https://www.forbes.com/sites/elizabethrushe/2018/11/22/the-beyond-burger-is-now-available-at-tesco-the-uks-largest-supermarket/#260250791461","https://www.booking.com/searchresults.html?aid=397594;label=gog235jc-1DCAEoggI46AdIH1gDaLsBiAEBmAEfuAEXyAEM2AED6AEB-AECiAIBqAID;sid=17c8ff66a97e2cdeb05450afd5a105c1;dest_id=-2140479;dest_type=city;highlighted_hotels=497786;nflt=ht_id%3D214%3Bht_id%3D219%3Bht_id%3D213%3Bht_id%3D229%3Bht_id%3D216%3Bht_id%3D209%3Bht_id%3D223%3Bht_id%3D212%3Bht_id%3D227%3Bht_id%3D215%3Bht_id%3D201%3Bht_id%3D208%3Bht_id%3D230%3Bht_id%3D232%3Bht_id%3D210%3Bht_id%3D220%3Bht_id%3D222%3Bht_id%3D224%3Bht_id%3D228;bhc_from_index=1;bhc_from_index=1","https://www.thefomofactory.com/","http://europe-re.com/fmo-pop-up-concept-store-opening-in-gothenburg-se/65770","https://www.seafoodsource.com/news/environment-sustainability/blockchain-trialed-for-sea-cucumber-traceability-in-japan","https://blog.ambrosus.com/in-depth-the-madagascar-bourbon-vanilla-supply-chain-on-amb-net-7f42ab0f5c9e","https://issuu.com/fashionrevolution/docs/fr_fashiontransparencyindex2018?e=25766662/60458846","https://www.monsterinsights.com/","https://www.wework.com/locations","https://youtu.be/NBYsK571vF0","https://www.beachub.com/work","https://www.lemonade.com/","https://www.30secondstofly.com/","https://www.mobilemarketer.com/news/marriott-makes-more-room-for-chatbots-to-enhance-guest-experiences/510117/","https://www.macrumors.com/2019/02/13/kroger-launches-kroger-pay-service/","https://www.weswap.com/en/","https://www.eurowag.com/pt-pt/reembolsos-de-impostos/","https://which-50.com/alipay-and-tourism-australia-trial-sydney-city-card-for-chinese-tourists/","https://www.goodnes.com/","https://www.theverge.com/2017/4/12/15259400/burger-king-google-home-ad-wikipedia","https://www.slu.edu/news/2018/august/slu-alexa-project.php","https://infarm.de/","http://www.growtogreen.com/","http://www.gizmag.com/fruit-silk-coating/43201/","http://www.phresh.io/index.html","http://www.madebycow.com.au/#worlds-first","https://www.indiegogo.com/projects/cupffee-the-edible-wafer-cup-for-your-coffee-innovation#/","http://www.davidideas.com/details/wikicells","https://thewaternetwork.com/article-FfV/water-soluble-packaging-f1Rl4Iex5XCR_9LD7rRjNA","http://www.vivosfilm.com/","http://solubag.cl/","http://chillcan.com/","http://www.impossiblefoods.com/faq/","http://www.goldandgreenfoods.com","http://beyondmeat.com/","https://oceanhuggerfoods.com/ahimi/","http://www.vbitesfoods.com/product/fish-free-smoked-salmon-slices-100g/","https://www.gardein.com/","http://ifoodbag.se/","http://smartflowersolar.com/","https://www.tesla.com/en_EU/solarroof?redirect=no","https://www.power-blox.com/","http://www.stem.com/","https://www.tesla.com/powerwall","http://www.physee.eu/","https://www.ibm.com/blockchain/solutions/food-trust","http://magiccandyfactory.com/events/","https://www.beeswrap.com/","https://tipa-corp.com/","https://www.packtin.com/en/","https://www.traxretail.com/","http://www.qopius.ai/","https://www.wiseshelf.com/","https://www.ses-imagotag.com/en/","https://www.displaydata.com/#Keyfacts-section","https://www.tronitag.com/us/","http://en.hanshow.com/#smart","https://www.pricer.com/","http://www.ontimesmart.com/","https://shelfierobot.com/","https://bizcargo.com/#/about","http://www.selitera.com/","https://www.sensei.tech/","https://www.advancingretail.org/solutions/caper","http://www.livello.com","https://www.aipoly.com/","https://itab.com/en/our-offer/checkout-arena/","https://ekiosk.com/en/","https://www.getmucho.com/","https://shelf.ai/","https://spoonshot.com/","https://vue.ai/ai-stylist/","https://www.tastry.com/","https://www.aquaponicsiberia.com/?lang=en","https://revibeenergy.com/","https://pro.hydrao.com/","https://www.retailquant.com/","https://eaternity.org/","https://linksquare.io/","http://www.aiconix.de/en","https://axonify.com","https://www.workwell.io/","https://www.beeapproved.co.uk/aboutus/","https://sonderpeople.com/","https://betalist.com/startups/wemonty","https://www.compt.io/?ref=betalist","http://www.morethancarrots.co.uk/","https://www.cogap.de/en","https://www.fitalety.com/","https://thea2milkcompany.com/","https://www.sourcemap.com/","https://www.thespikeapp.com/","https://emma.health/","http://www.emulsar.com/","https://www.nodoughpizza.com/","http://www.bolfoods.com","https://zveetz.com/","http://hello.keep-warranty.com/","https://oko.ai/","http://www.inui-studio.com","https://www.leapmotion.com/","https://get-nourished.com/","https://bulkboxfoods.com","https://www.menunfc.com/","https://unbabel.com/","https://www.wasteless.co/","https://www.cambridge-crops.com/","http://www.pikkart.com","http://www.trusttm.com/en/","https://luckyironfish.com","https://www.yusadrinks.com/","https://spirugrow.com/","http://inl.int/life-science/nano-for-food/","https://syngja.dk/","https://www.splosh.com/","https://www.greenbiz.com/article/loops-launch-brings-reusable-packaging-worlds-biggest-brands","https://www.dropwater.co/","http://www.framieapp.com/","https://youclap.tech/","https://olioex.com/","https://www.twoosk.com/page/about-us","https://www.joinforge.com/","https://tubularlabs.com/","https://www.beyondmeat.com/","https://www.quorn.co.uk","https://wholifoods.com/","https://cuisinesoleil.com/en/","http://algamafoods.com/","https://kriket.be/","https://seamorefood.com/","https://www.sensbar.com/en","https://www.eatizz.com/en/","https://movingworlds.org/international-corporate-volunteering","https://werk.co/","https://ambrosus.com/","https://www.nutrasign.io/en/","https://www.sap.com/products/batch-product-traceability.html","https://traace.io/","http://www.smartlogo.it/","https://uwinloc.com/","https://bettercotton.org/","https://www.toptal.com/careers","https://www.knotel.com","https://www.smartaisle.io/","https://www.bitext.com/","https://www.3d-berlin.com/en/","https://www.eyeconic.com/help-me/virtual-try-on","https://www.goinstore.com/","http://ecodyger.com/","https://www.elvisandkresse.com/","http://www.greenjournal.co.uk/2015/07/transparent-solar-panels-2/","https://www.curbed.com/2017/6/19/15828644/solar-paint-renewable-energy-rmit-university","http://www.channelnewsasia.com/news/singapore/nus-scientists-roll-out-diabetic-friendly-bread-8184586","http://www.deakin.edu.au/research/research-news/articles/scientists-unscramble-egg-allergens","https://www.nanowerk.com/news/newsid=1441.php","http://eot.pt/en/","https://www.docplanner.com/about-us","https://www.magnomics.pt/","https://www.mydxlife.com/","https://kubo.education/","https://thebookofeveryone.com/","http://www.ionseed.eu/","https://situm.es/en","https://www.nevisq.com/home","http://www.cloqwerk.com/home.html","http://swiftwallet.io/","https://pingpilot.com/","https://www.optionizr.com/","https://www.themotion.com/","https://www.omknee.com/","https://agrimp.com/","http://gcourage.com/","https://www.flow.ai/","https://kami.ai/","https://www.coolerscreens.com/","https://www.affectiva.com/","https://profila.com/","https://www.adpack.tv/","http://www.arpa.tech/indexe.html","https://www.publico.pt/2019/01/11/p3/noticia/spray-portugues-quer-subsituir-o-plastico-na-conservacao-de-alimentos-1857507#gs.yzRGWbEh","https://www.naturalproductsglobal.com/europe/unilver-adds-vegetarian-butcher-to-growing-plant-based-portfolio/","https://www.marketwatch.com/story/kroger-rolls-out-driverless-cars-to-deliver-groceries-2018-12-18?fbclid=IwAR3_YflqEDM1O38t98aCk6ro1OT_KJ_kbVVGwPw-BXHV8iTlfbMssDSZ09A"
    "https://www.thetimes.co.uk/article/ask-james-dyson-jfrhm8nchzg",
// "https://www.netflix.com/pt-en/title/80988062",
// "https://www.news.com.au/lifestyle/food/drink/cocacola-launches-new-adult-drink-that-mixes-coffee-with-soft-drink/news-story/b6fd65b314ea2c92ced28824b47df549?utm_source=DesignTAXI&utm_medium=DesignTAXI&utm_term=DesignTAXI&utm_content=DesignTAXI&utm_campaign=DesignTAXI",
// "https://www.walmart.com/cp/1908812?u1=IS,SofADaVergaraJustMadetheUnder-$40JeansYourButtHasAlwaysWanted,lreilly805,FAS,ART,3417806,201902,I&oid=645206.1&wmlspartner=93xLBvPhAeE&sourceid=29947390703266111865&affillinktype=10&veh=aff",
// "https://www.kickstarter.com/projects/67420768/mim-x-the-first-smartwatch-with-invisible-display",
// "https://www.jnsq.com/",
// "http://fortune.com/2016/09/22/pepsico-restaurant-kola-house/",
// "https://www.tetrapak.com/packaging/tetra-rex",
// "http://www.skippingrockslab.com",
// "https://www.ebayinc.com/stories/blogs/tech/interactive-visual-search/",
// "http://www.ynap.com/news/net-a-porter-mr-porter-announce-enhanced-personal-shopping-services-for-top-customers/",
// "https://www.businessoffashion.com/articles/bof-exclusive/inside-farfetchs-store-of-the-future",
// "https://www.youtube.com/watch?v=IIW3l-ENHdA",
// "https://pay.google.com",
// "https://www.amazon.com/Dash-Buttons/b?ie=UTF8&node=10667898011",
// "https://www.standardcognition.com/app/",
// "https://www.finery.com/",
// "https://www.miele.co.uk/domestic/1563.htm?info=200107190-ZPV",
// "https://digit.co/",
// "https://www.munchingmongoose.co.za/",
// "https://www.thebodyshop.com/en-us/about-us/against-animal-testing",
// "https://www.thehersheycompany.com/en_us/whats-inside.html",
// "https://www.whatsinmyfood.com/",
// "https://www.food-interrupted.com/",
// "https://www.newscientist.com/article/2190259-ai-created-images-of-food-just-by-reading-the-recipes/",
// "https://www.youtube.com/channel/UCGYyLEdGEQjVVfwlzOB5Kng",
// "https://lrmonline.com/news/keeping-up-with-animation-trends-through-pixar-university/",
// "https://www.thenational.ae/business/economy/carrefour-s-new-school-will-train-2-500-managers-for-the-digital-age-of-retail-1.821752",
// "http://www.carrefour.com/current-news/carrefour-drive-opens-a-first-pick-up-point-on-a-technology-campus-in-belgium",
// "http://www.gifts-today.co.uk/news/carrefour_launches_afterwork_pickup_point_for_belgian_office_workers.aspx",
// "https://www.roam.co/business",
// "https://retaildesignblog.net/2018/12/14/a-new-spot-for-digital-creators-in-warsaw/",
// "https://www.theassemblage.com/",
// "http://www.geltor.com/n-collage/",
"https://www.poulehouse.fr/",
"https://www.undercurrentnews.com/2017/07/28/tesco-collaborates-with-turkish-bass-bream-farmers-uk-processors-on-new-humane-slaughtering-method/",
// "https://www.thequint.com/lifestyle/life/ariels-share-the-load-campaign-gender-disparity-video",
// "https://www.youtube.com/watch?v=26qmJzTCRG4",
// "https://edition.cnn.com/travel/article/aeromexico-dna-discount-travel-ad-video/index.html",
// "https://www.uber.com/en-CA/blog/biggame/",
// "https://www.youtube.com/playlist?list=PLtF-ZfyeXJcew2fYXmaLEdggPdKdjn7kL",
// "https://www.adweek.com/brand-marketing/story-behind-one-most-beautiful-real-moments-advertising-158478/",
// "https://www.functionofbeauty.com/about/",
// "https://prose.com/",
// "https://www.skillshare.com/",
// "https://www.udemy.com",
// "https://www.bizjournals.com/bizwomen/news/latest-news/2018/06/craft-retailer-joann-tests-new-store-concept.html",
// "https://www.hyundai.news/eu/technology/hyundai-motor-group-ventures-further-into-new-robotics-industry/",
// "http://www.lowesinnovationlabs.com/exosuits/",
// "https://news.samsung.com/global/video-meet-the-samsung-bots-your-companions-of-the-future",
// "https://www.marksandspencer.com/c/food-to-order/adventures-in-food/plant-kitchen",
// "http://crussh.com/powered-by-plants",
// "https://www.tesco.com/groceries/en-GB/zone/wicked-kitchen/",
// "https://www.nutrinohealth.com/",
// "https://www.startup.si/en-us/startup/151/vinegar-and-ketchup-as-innovative-functional-foods",
// "https://www.bloomberg.com/news/articles/2018-11-05/senior-citizens-are-replacing-teenagers-at-fast-food-joints?srnd=premium",
// "https://www.apyball.com/",
// "https://www.warbyparker.com",
// "https://techcrunch.com/2019/01/29/facebook-project-atlas/",
// "https://www.arket.com/en_eur/about.html",
// "https://brandless.com/",
// "https://atap.google.com/jacquard/",
// "https://driving.ca/bmw/7-series/auto-news/news/how-it-works-bmw-gesture-control",
// "http://digitaldetoxholidays.com/",
// "https://www.adweek.com/agencies/hulu-reveals-the-strategy-behind-its-partnership-with-instagrams-viral-world-record-egg/",
// "https://www.rei.com/blog/social/rei-employees-get-outside-and-play-with-yay-days",
// "https://allbulkfoods.com",
// "https://thesourcebulkfoods.com.au",
// "http://www.jackdanielscoffee.com/",
// "https://www.stryyk.com/",
// "https://www.ogilvy.com/feed/playing-it-safe-advertising-in-super-bowl-liii/",
// "https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/",
// "https://www.kelloggs.com/en_US/brands/happy-inside.html#num=12",
// "https://www.realfoodrealstories.org/",
// "https://www.arodadaalimentacao.pt/",
// "https://www.inc.com/bill-murphy-jr/amazon-is-recruiting-entrepreneurs-to-local-start-delivery-companies-heres-why-i-think-some-people-could-get-rich.html",
// "https://medium.com/@jinghanhao/experiencing-new-retail-in-china-hema-fresh-a5ba4c94da22",
// "https://www.justbeedrinks.co.uk/",
// "https://www.bulknationusa.com/",
// "https://sweatco.in/",
// "https://home.barclays/news/2017/02/supporting-older-workers/",
// "https://news.sap.com/2015/03/young-old-powerful-combination/",
// "http://www.eyalter.com/en/tunnel-decision/",
// "https://www.forbes.com/sites/walterloeb/2016/08/08/best-buy-focuses-on-shop-in-shop-sales-and-is-making-changes-for-growth/#66875e575bca",
// "https://shop.nordstrom.com/content/nordstrom-local",
// "https://dreamerybycasper.com/",
// "https://www.festfoods.com/blog/2-new-cheese-snacks-are-grate-go",
// "https://econsultancy.com/11-examples-of-marketing-campaigns-starring-youtubers/",
// "https://www.mcdonalds.pt/ementa/produtos/mcveggie/",
// "https://www.forbes.com/sites/elizabethrushe/2018/11/22/the-beyond-burger-is-now-available-at-tesco-the-uks-largest-supermarket/#260250791461",
// "https://www.booking.com/searchresults.html?aid=397594;label=gog235jc-1DCAEoggI46AdIH1gDaLsBiAEBmAEfuAEXyAEM2AED6AEB-AECiAIBqAID;sid=17c8ff66a97e2cdeb05450afd5a105c1;dest_id=-2140479;dest_type=city;highlighted_hotels=497786;nflt=ht_id%3D214%3Bht_id%3D219%3Bht_id%3D213%3Bht_id%3D229%3Bht_id%3D216%3Bht_id%3D209%3Bht_id%3D223%3Bht_id%3D212%3Bht_id%3D227%3Bht_id%3D215%3Bht_id%3D201%3Bht_id%3D208%3Bht_id%3D230%3Bht_id%3D232%3Bht_id%3D210%3Bht_id%3D220%3Bht_id%3D222%3Bht_id%3D224%3Bht_id%3D228;bhc_from_index=1;bhc_from_index=1",
// "https://www.thefomofactory.com/",
// "http://europe-re.com/fmo-pop-up-concept-store-opening-in-gothenburg-se/65770",
// "https://www.seafoodsource.com/news/environment-sustainability/blockchain-trialed-for-sea-cucumber-traceability-in-japan",
// "https://blog.ambrosus.com/in-depth-the-madagascar-bourbon-vanilla-supply-chain-on-amb-net-7f42ab0f5c9e",
// "https://issuu.com/fashionrevolution/docs/fr_fashiontransparencyindex2018?e=25766662/60458846",
// "https://www.monsterinsights.com/",
// "https://www.wework.com/locations",
// "https://youtu.be/NBYsK571vF0",
// "https://www.beachub.com/work",
// "https://www.lemonade.com/",
// "https://www.30secondstofly.com/",
// "https://www.mobilemarketer.com/news/marriott-makes-more-room-for-chatbots-to-enhance-guest-experiences/510117/",
// "https://www.macrumors.com/2019/02/13/kroger-launches-kroger-pay-service/",
// "https://www.weswap.com/en/",
// "https://www.eurowag.com/pt-pt/reembolsos-de-impostos/",
// "https://which-50.com/alipay-and-tourism-australia-trial-sydney-city-card-for-chinese-tourists/",
// "https://www.goodnes.com/alexa-skill",
// "https://www.theverge.com/2017/4/12/15259400/burger-king-google-home-ad-wikipedia",
// "https://www.slu.edu/news/2018/august/slu-alexa-project.php",
// "https://www.publico.pt/2019/01/11/p3/noticia/spray-portugues-quer-subsituir-o-plastico-na-conservacao-de-alimentos-1857507#gs.yzRGWbEh",
// "https://www.naturalproductsglobal.com/europe/unilver-adds-vegetarian-butcher-to-growing-plant-based-portfolio/",
// "https://www.marketwatch.com/story/kroger-rolls-out-driverless-cars-to-deliver-groceries-2018-12-18?fbclid=IwAR3_YflqEDM1O38t98aCk6ro1OT_KJ_kbVVGwPw-BXHV8iTlfbMssDSZ09A",
// "https://www.ibm.com/blockchain/solutions/food-trust",
// "https://swipii.com/",
// "http://magiccandyfactory.com/events/",
// "https://www.beeswrap.com/",
// "https://tipa-corp.com/",
// "https://www.packtin.com/en/",
// "http://www.qopius.ai/",
// "https://www.wiseshelf.com/",
// "https://www.displaydata.com/#Keyfacts-section",
// "https://www.tronitag.com/us/",
// "http://en.hanshow.com/#smart",
// "https://www.pricer.com/",
// "http://www.ontimesmart.com/",
// "https://shelfierobot.com/",
// "https://bizcargo.com/#/about",
// "http://www.selitera.com/",
// "https://www.sensei.tech/",
// "https://www.advancingretail.org/solutions/caper",
// "http://www.livello.com",
// "https://www.aipoly.com/",
// "https://itab.com/en/our-offer/checkout-arena/",
// "https://ekiosk.com/en/",
// "https://www.getmucho.com/",
// "https://shelf.ai/",
// "https://spoonshot.com/",
// "https://vue.ai/ai-stylist/",
// "https://www.tastry.com/",
// "https://www.aquaponicsiberia.com/?lang=en",
// "https://revibeenergy.com/",
// "https://pro.hydrao.com/",
// "https://www.retailquant.com/",
// "https://eaternity.org/",
// "https://linksquare.io/",
// "http://www.aiconix.de/en",
// "https://axonify.com",
// "https://www.workwell.io/",
// "https://www.beeapproved.co.uk/aboutus/",
// "https://sonderpeople.com/",
// "https://betalist.com/startups/wemonty",
// "https://www.compt.io/?ref=betalist",
// "http://www.morethancarrots.co.uk/",
// "https://www.cogap.de/en",
// "https://www.fitalety.com/",
// "https://thea2milkcompany.com/",
// "https://www.sourcemap.com/",
// "https://www.thespikeapp.com/",
// "https://emma.health/",
// "http://www.emulsar.com/",
// "https://www.nodoughpizza.com/",
// "http://www.bolfoods.com",
// "https://zveetz.com/",
// "http://hello.keep-warranty.com/",
// "https://oko.ai/",
// "http://www.inui-studio.com",
// "https://www.leapmotion.com/",
// "https://get-nourished.com/",
// "https://bulkboxfoods.com",
// "https://www.menunfc.com/",
// "https://unbabel.com/",
// "https://www.wasteless.co/",
// "https://www.cambridge-crops.com/",
// "http://www.pikkart.com",
// "http://www.trusttm.com/en/",
// "https://luckyironfish.com",
// "https://www.yusadrinks.com/",
// "https://spirugrow.com/",
// "http://inl.int/life-science/nano-for-food/",
// "https://syngja.dk/",
// "https://www.splosh.com/",
// "https://www.greenbiz.com/article/loops-launch-brings-reusable-packaging-worlds-biggest-brands",
// "https://www.dropwater.co/",
// "http://www.framieapp.com/",
// "https://youclap.tech/",
// "https://olioex.com/",
// "https://www.twoosk.com/page/about-us",
// "https://www.joinforge.com/",
// "https://tubularlabs.com/",
// "https://www.beyondmeat.com/",
// "https://www.quorn.co.uk",
// "https://wholifoods.com/",
// "https://cuisinesoleil.com/en/",
// "http://algamafoods.com/",
// "https://kriket.be/",
// "https://seamorefood.com/",
// "https://www.sensbar.com/en",
// "https://www.eatizz.com/en/",
// "https://movingworlds.org/international-corporate-volunteering",
// "https://werk.co/",
// "https://ambrosus.com/",
// "https://www.nutrasign.io/en/",
// "https://www.sap.com/products/batch-product-traceability.html",
// "https://traace.io/",
// "http://www.smartlogo.it/",
// "https://uwinloc.com/",
// "https://bettercotton.org/",
// "https://www.toptal.com/careers",
// "https://www.knotel.com",
// "https://www.smartaisle.io/",
// "https://www.bitext.com/",
// "https://www.3d-berlin.com/en/",
// "https://www.eyeconic.com/help-me/virtual-try-on",
// "https://www.goinstore.com/",
// "http://ecodyger.com/",
// "https://www.elvisandkresse.com/",
// "http://eot.pt/en/",
// "https://www.docplanner.com/about-us",
// "https://kubo.education/",
// "https://thebookofeveryone.com/",
// "http://www.ionseed.eu/",
// "https://situm.es/en",
// "https://www.nevisq.com/home",
// "http://www.cloqwerk.com/home.html",
// "http://swiftwallet.io/",
// "https://pingpilot.com/",
// "https://www.optionizr.com/",
// "https://www.themotion.com/",
// "https://www.omknee.com/",
// "https://agrimp.com/",
// "http://gcourage.com/",
// "https://www.flow.ai/",
// "https://kami.ai/",
// "https://www.coolerscreens.com/",
// "https://www.affectiva.com/",
// "https://profila.com/",
// "https://www.adpack.tv/",
// "http://www.arpa.tech/indexe.html",
// "http://sightcorp.com/crowdsight/",
// "https://prism.com/",
// "http://lab4motion.com/",
// "http://www.infor.com/product-summary/retail/demand-management/",
// "https://azure.microsoft.com/pt-pt/services/machine-learning/",
// "https://www.blue-yonder.com/em",
// "https://www.activitystream.com/",
// "http://www.presenso.com/technology-industrial-analytics/",
// "http://www.machinametrica.com/predictive-maintenance-software-platform.html",
// "https://www.add-for.com/predictive-maintenance/",
// "https://www.advelvet.com",
// "https://www.perfectprice.com/product",
// "https://dressupai.bitbucket.io/signup/",
// "https://www.sentient.ai/aware/",
// "https://www.liftigniter.com/solutions/",
// "https://www.tarent.de/en/services/products/sellfio",
// "http://heptasense.com/",
// "https://www.forter.com/",
// "https://feedzai.com/",
// "https://www.amazon.com/Amazon-Echo-Bluetooth-Speaker-with-WiFi-Alexa/dp/B00X4WHP5E",
// "https://www.jibo.com/",
// "https://infarm.de/",
// "http://www.growtogreen.com/",
// "https://aquaponics.com/aquaponic-systems/",
// "http://pentairaes.com/commercial-solutions/commercial-aquaponics",
// "https://www.facebook.com/pg/koaloponics/about/",
// "https://www.23andme.com/en-int/",
// "http://www.heartgenetics.com/about-us/",
// "http://www.gizmag.com/fruit-silk-coating/43201/",
// "https://apeelsciences.com/",
// "https://www.hazeltechnologies.com/",
// "http://www.bionatsolutions.com/",
// "http://www.madebycow.com.au/#worlds-first",
// "https://www.cdxlife.com",
// "http://www.magnomics.pt",
// "http://www.labonfoil.eu/",
// "https://cue.me/product",
// "https://www.microsoft.com/en-us/hololens",
// "https://www.vuzix.com/",
// "http://www.ccg.pt/",
// "https://itpeopleinnovation.com/",
// "http://www.foodqualitynews.com/R-D/Firefly-Dx-RT-PCR-pathogen-detection-system-for-food-safety",
// "http://www.c2sense.com/",
// "http://www.ucd.ie/refrig/",
// "http://www.iris-eng.com/",
// "https://www.sintef.no/en/latest-news/x-ray-scanning-to-guarantee-meat-tenderness/",
// "http://tellspec.com/en/",
// "https://noticias.up.pt/nanotecnologia-pode-contribuir-para-um-melhor-vinho/",
// "http://sensorindicator.com/",
// "https://chain.com",
// "https://ripple.com",
// "http://kit.farmx.co/",
// "https://www.wisecrop.com/pt/",
// "https://www.agroop.net/en/whatwedo",
// "https://www.nfcworld.com/2014/05/22/329286/telstra-digital-uses-nfc-broadband-customers-access-instant-help/",
// "https://econsultancy.com/blog/65307-five-retailers-using-nfc-and-rfid-to-enhance-shopping-but-do-they-work",
// "http://www.sonova.com/en/features/3d-printing-technology-improved-hearing",
// "https://www.jweel.com/en/",
// "https://www.starship.xyz/",
// "https://piaggiofastforward.com/gita",
// "https://www.engadget.com/2018/10/04/toyota-softbank-monet/?guccounter=1&guce_referrer_us=aHR0cHM6Ly93d3cuZ29vZ2xlLnB0Lw&guce_referrer_cs=fDjI0Mr5EA-YXelsnfyxiQ",
// "http://www.karispro.de/",
// "https://www.dematic.com/en-us/products/products-overview/agv-systems/",
// "http://www.rethinkrobotics.com/sawyer/",
// "https://www.amazonrobotics.com/#/",
// "http://www.kuka-robotics.com/en/",
// "https://new.huji.ac.il/en/article/28743",
// "https://www.freestylelibre.co.uk/libre/",
// "http://www.myzone.org/meet-the-mz3/",
// "https://www.skulpt.me/",
// "http://www.aao.org/newsroom/news-releases/detail/programmable-electronic-glasses-provide-children-e",
// "https://vitalconnect.com/solutions/vitalpatch/",
// "https://owletbabycare.co.uk/",
// "https://www.kinsahealth.co/products/",
// "http://en.laevo.nl/",
// "http://www.suitx.com/phoenix",
// "http://nuada.pt/",
// "https://www.sri.com/brochures/superflex-soft-biofidelic-actuated-exosuit",
// "http://swordhealth.com/",
// "https://wearkinetic.com/",
// "https://www.truposture.com/",
// "https://www.uprightpose.com/",
// "http://prana.co/",
// "http://www.plux.info/index.php/en/",
// "https://www.percko.com",
// "http://www.juvolabs.com/",
// "https://ouraring.com/",
// "https://www.indiegogo.com/projects/eversleep-wake-up-refreshed-5-in-1-sleep-tracker-health-technology--2#/",
// "http://www.kabaq.io",
// "http://www.trylive.com/solutions/trylive-eyewear-virtual-mirror/overview",
// "http://memorymirror.com/",
// "http://www.catalyst-direct.co.uk/retail_catalyst_delay_mirror.php",
// "https://m.blog.naver.com/711sns/221006724498",
// "https://selfiepay.co/",
// "http://www.mytouchpayments.com/default.aspx",
// "http://sixense.com/vretail",
// "https://www.ikea.com/ms/en_US/this-is-ikea/ikea-highlights/Virtual-reality/index.html",
// "http://www.jaguarlandrover.com/news/2017/01/jaguar-land-rover-customers-immerse-themselves-virtual-vehicles",
// "http://www.byar.pt/",
// "http://www.ubimax.com/en/",
// "https://gizmodo.com/13-fascinating-farming-robots-that-will-feed-our-future-1683489468",
// "http://www.simberobotics.com/",
// "https://www.softbankrobotics.com/us/pepper",
// "http://followinspiration.pt/",
// "https://www.poweredbyheatgen.com/",
// "https://www.wired.com/2014/08/high-tech-frozen-yogurt-that-comes-in-edible-packaging/#slide-1",
// "https://www.cortecvci.com/products/vpci-packaging-products/ecosol-water-soluble-packaging-solution/",
// "https://www.monosol.com/applications/food-grade/",
// "http://solubag.cl/",
// "https://www.home.queuehop.com/",
// "http://news.panasonic.com/global/topics/2017/46190.html",
// "https://www.home.barclaycard/media-centre/press-releases/barclaycard-trials-new-queue-less-checkout-payment-concept-grab-go.html",
// "http://chillcan.com/",
// "http://www.ses-imagotag.com",
// "http://en.hanshow.com",
// "http://www.pricer.com",
// "https://www.memphismeats.com",
// "https://www.supermeat.com/",
// "http://www.impossiblefoods.com/faq/",
// "http://www.goldandgreenfoods.com",
// "http://beyondmeat.com/",
// "https://oceanhuggerfoods.com/ahimi/",
// "https://www.vbites.com/product/fish-free-smoked-salmon-slices/",
// "https://www.gardein.com/",
// "http://www.perfectdayfoods.com/",
// "https://realvegancheese.org/",
// "https://www.ripplefoods.com/original-plant-milk/",
// "http://goodkarmafoods.com/products/",
// "https://fieldroast.com/chao-creamery/",
// "https://daiyafoods.com/plant-based-living/#lifestyle",
// "http://www.bitcliq.com/bigeye/",
// "http://arc-net.io",
// "http://www.thenotcompany.com",
// "http://www.planetorganic.com/follow-your-heart-veganegg-114g/23865/",
// "https://www.bonappetit.com/test-kitchen/ingredients/article/aquafaba-health-benefits",
// "https://followyourheart.com/products/",
// "http://www.bugsolutely.com",
// "https://entocube.com/en/",
// "https://www.power-blox.com/",
// "http://www.stem.com/",
// "https://www.tesla.com/powerwall",
// "http://www.physee.eu/",
// "http://rainharvesting.co.uk/",
// "https://water.xprize.org/",
// "http://www.warkawater.org/",
// "http://www.serioussimulations.com/",
// "http://www.agility3.co.uk/",
// "http://www.kelvinretail.com/",
// "https://soprism.com/",
// "https://www.sas.com/en_us/solutions/customer-intelligence.html",
// "http://www.musion3d.co.uk/services/telepresence/",
// "https://www.kickstarter.com/projects/2029950924/holovect-holographic-vector-display/description",
// "https://www.realfiction.com/solutions/dreamoc-hd3",
// "https://www.engadget.com/2016/09/28/volume-is-a-1-000-holographic-display-for-your-home/",
// "https://phys.org/news/2015-08-quantum-dot-solar-windows-non-toxic.html",
// "http://www.nanocotechnologies.com/what-we-do/applications/lighting",
// "https://www.technologyreview.com/s/414035/quantum-dot-lighting/",
// "http://www.innoscentia.com/",
// "https://materdynamics.com/",
// "http://freshpoint-tti.com/",
// "https://www.sigfox.com/",
// "https://www.semtech.com/lora",
// "https://www.telecom.pt/pt-pt/media/noticias/paginas/2018/novembro/narrowband-iot-.aspx",
// "https://www.vodafone.com/business/iot/managed-iot-connectivity/nb-iot",
// "https://www.hivetracker.io/",
// "https://www.sherlock.bike/en/",
// "https://secure.thetrackr.com/",
// "http://www.sensoriafitness.com/",
// "https://www.mimobaby.com/",
// "https://eyesee-drone.com/?lang=en",
// "http://www.dronescan.co/",
// "http://www.cosyrobo.com/#home",
// "https://www.sonae.pt/pt/inovacao/projetos/shopview/",
// "https://www.tarent.de/en/product/snabble-self-scanning/",
// "https://traxretail.com/technology/",
// "https://www.pensasystems.com/",
// "https://gimbal.com/",
// "https://estimote.com/",
// "https://kontakt.io/",
// "http://connect-robotics.com/",
// "https://www.amazon.com/Amazon-Prime-Air/b?ie=UTF8&node=8037720011",
// "http://www.bbc.com/news/technology-31129804",
// "http://mode.ai/#/menu",
// "http://www.automaise.com/",
// "https://www.sensitile.com/",
// "http://edition.cnn.com/2015/05/14/tech/bioconcrete-delft-jonkers/index.html",
// "https://www.pilkington.com/en-gb/uk/householders/types-of-glass/energy-efficient-glass/low-emissivity-glass",
// "https://www.aerogel.com/",
// "https://www.woolcool.com/",
// "http://www.naturalbluethermal.com/",
// "https://wiivv.com/",
// "https://www.unmade.com/",
// "https://repreve.com/",
// "http://www.lenzing-fibers.com/en/tencel/",
// "http://www.econyl.com/",
// "http://smartflowersolar.com/",
// "https://www.tesla.com/en_EU/solarroof?redirect=no",
// "http://www.greenjournal.co.uk/2015/07/transparent-solar-panels-2/",
// "https://www.curbed.com/2017/6/19/15828644/solar-paint-renewable-energy-rmit-university",
// "http://www.channelnewsasia.com/news/singapore/nus-scientists-roll-out-diabetic-friendly-bread-8184586",
// "http://www.deakin.edu.au/research/research-news/articles/scientists-unscramble-egg-allergens",
// "https://www.nanowerk.com/news/newsid=1441.php",
// "https://observador.pt/2018/07/29/bolas-de-berlim-de-spirulina-sao-novidade-nas-praias-algarvias-este-verao/",
// "https://www.storemagazine.pt/tecnologia/item/3830-reciclaya-%C3%A9-a-nova-app-do-carrefour-em-palma-de-maiorca.html?utm_source=dlvr.it&utm_medium=twitter",
// "https://finance.yahoo.com/news/ge-adopt-vr-technology-htm-220610798.html?.tsrc=applewf&guccounter=1",
// "https://www.avanieco.com/",
// "https://www.getquip.com/",
// "https://www.24bottles.com",
// "https://www.clarifruit.com/",
// "https://ovie.life/",
// "https://www.novameat.com/",
// "https://infarm.com/",
// "https://ogarden.org/en/",
// "http://portugalbugs.pt/",
// "https://www.civalue.com/",
// "https://www.farmersfridge.com/",
// "https://www.kencko.com/",
// "http://www.tradearabia.com/news/OGN_348371.html",
// "http://www.pavegen.com",
// "https://www.theverge.com/2019/1/15/18167388/nike-self-lacing-shoes-adapt-bb-smart-bluetooth-app-features-battery-life-price-release-date",
// "https://meetzipongo.com",
// "https://www.museumoficecream.com/",
// "https://www.telegraph.co.uk/business/2018/01/31/lidl-launches-online-chatbot-recommends-wine-based-budget-food/",
// "https://www.wired.com/story/your-time-on-facebook-digital-wellness/?utm_source=twitter&utm_brand=wired&utm_medium=social&utm_social-type=owned&mbid=social_twitter&utm_campaign=wired",
// "https://www.kickstarter.com/projects/1366585536/moon-cycle-bakery-hormone-balancing-treats?utm_campaign=Innovation%20of%20the%20Day%20&utm_source=hs_email&utm_medium=email&utm_content=60096638&_hsenc=p2ANqtz--SrtwWJLUnfO3n-eYI3Ex9kh0lcHT3Ib7wZ9M_mIWwFdDlakwf0BcavpNS9P-iH3UBIb1hfF1JT9AiL3oIAX3mO2fnfA&_hsmi=60111980",
// "https://amp.fastcompany.com/40517697/evian-will-make-all-its-water-bottles-out-of-100-recycled-plastic",
// "https://www.bevindustry.com/articles/90933-drinkfinity-offers-personalized-beverage-options",
// "https://magg.pt/2018/02/18/kombucha-a-bebida-chinesa-que-faz-bem-a-tudo/",
// "https://www.youtube.com/watch?v=RuUSc53Xpeg&feature=share",
// "https://www.lavanguardia.com/comer/20180417/442653502810/carrefour-insectos.html",
// "https://www.yonest.com/",
// "https://www.hapi.com/product/hapifork",
// "https://rebbl.co/",
// "https://www.youtube.com/watch?v=4DKrcpa8Z_E",
// "https://www.spoon.guru/usa/",
// "https://www.vegware.com/#",
// "https://www.youtube.com/watch?v=CJub8XYmzt4",
// "https://www.fastcompany.com/90308307/gig-economy-platform-thumbtack-is-helping-its-users-get-benefits",
// "https://hbr.org/2018/03/why-you-should-rotate-office-seating-assignments",
// "https://grandeconsumo.com/carrefour-simplifica-a-compra-online-com-auto-add/?utm_source=Newsletter+19%2F02%2F2019&utm_medium=email&utm_term=https%3A%2F%2Fgrandeconsumo.com%2Fcarrefour-simplifica-a-compra-online-com-auto-add%2F&utm_content&utm_campaign=Newsletter+Grande+Consumo+19%2F02%2F2019#.XG0duPn7Q2x",
// "https://www1.folha.uol.com.br/mercado/2019/01/carrefour-vai-auditar-abatedores-e-exigir-cameras-para-bem-estar-animal.shtml",
// "https://www.givelegacy.com",
// "http://www.imagoai.com/",
// "http://www.planetbiometrics.com/article-details/i/9977/desc/caixabank-reveals-face-recognition-atms/",
// "https://findbiometrics.com/aerospace-defense-contractor-bio-key-security-601303/",
// "https://www.animalife.pt/pt/bsa/programa",
// "https://books.google.pt/books?id=PdsQDAAAQBAJ&lpg=PA110&ots=V69XVRqTLY&dq=SUPERMARKET%20MULTICULTURAL%20CITIES&pg=PA109#v=onepage&q&f=false",
// "https://www.forbes.com/sites/laurenhallanan/2018/10/24/i-shopped-at-hema-with-locals-heres-what-new-retail-was-really-like/",
// "https://impossiblefoods.com/food/",
// "https://www.brookings.edu/research/automation-and-artificial-intelligence-how-machines-affect-people-and-places/",
// "https://www.youtube.com/watch?v=KTAg936uoic",
// "https://www.ucsf.edu/news/2018/12/412946/artificial-intelligence-can-detect-alzheimers-disease-brain-scans-six-years",
// "https://sociable.co/technology/can-a-robot-write-a-symphony-the-blossoming-artistic-talent-of-modern-day-ai/",
// "https://www.theguardian.com/lifeandstyle/2018/may/19/fake-steak-supermarkets-flexitarians-meat-free-burgers",
// "https://motherboard.vice.com/en_us/article/gydgvj/americans-cut-the-cord-2030-study-cable-tv",
// "https://www.weforum.org/agenda/2018/05/sustainable-products-good-for-the-world-or-expensive-hype/",
// "https://www.cnbc.com/2018/06/08/inside-mcdonalds-new-250-million-headquarters.html",
// "http://www.asahi.com/ajw/articles/AJ201806120064.html",
// "https://medium.com/world-economic-forum/cutting-money-transfer-fees-could-unlock-15bn-for-developing-countries-heres-how-985f606b6351",
// "https://liveforlivemusic.com/news/metallica-setlists-spotify-data/",
// "https://www.reuters.com/article/us-volkswagen-emissions-combustion/volkswagen-says-last-generation-of-combustion-engines-to-be-launched-in-2026-idUSKBN1O32O6",
// "https://qz.com/1486377/global-shipper-maersk-says-it-will-eliminate-fossil-fuels-by-2050/",
// "https://sonaesystems.sharepoint.com/:v:/s/SHIFT/EXhgUr0pmmRDjsFP2-saIIoBAUOK4_TEeBVo85Hr1EMSrA?e=SYqiSV",
// "https://www.fastcompany.com/90287861/the-future-of-the-13b-food-delivery-industry-rests-on-better-shelves",
// "https://www.eatsa.com/",
// "https://techcrunch.com/2018/07/11/olio/",
// "https://techcrunch.com/2019/02/25/walmart-acquires-israels-aspectiva-which-analyses-ugc-to-recommend-products-to-shoppers/",
// "https://www2.deloitte.com/insights/us/en/topics/talent/deloitte-millennial-survey.html",
// "https://www.entrepreneur.com/article/315325",
// "https://www.wired.com/story/rotten-tomatoes-captain-marvel-trolls/",
// "https://3degreesinc.com/",
// "https://www.fastcompany.com/90311622/etsy-just-became-the-first-global-ecommerce-company-to-offset-all-of-its-shipping-emissions",
// "https://www.forbes.com/sites/kaytiezimmerman/2018/05/02/this-company-is-letting-its-employees-choose-their-rewards/#7d78a7946484",
// "https://business.linkedin.com/talent-solutions/blog/company-culture/2018/companies-letting-employees-choose-perks",
// "https://www.meatfreemondays.com/",
// "https://www.foodlogiq.com/",
// "https://www.foodethicscouncil.org/resources/ethicaltools/what-is-food-ethics.html",
// "https://www.cleanlabelproject.org/",
// "https://youtu.be/nfK29VANu_0",
"https://www.nidolove.com/nido-fortigrow"
];
var metalist = [];

function crawl(callback) {
    progress = sitelist.length;
    for (site in sitelist) {
        // var url = 'http://www.thprd.org/activities/schedules/aquatic-fitness-water-fitness-class?cs_id=' + pools[pool];
        var url = sitelist[site];

        request(url, (function(site) { return function(err, resp, body) {
            if (body) {
                console.log(site,"|",chalk.green(sitelist[site]));
                $ = cheerio.load(body);
                // DEFINE METADATA FIELDS
                titleobj = $('meta[property="og:title" i]').eq(0).attr('content');
                console.log("(1) | ",titleobj);
                if (!titleobj) {titleobj = $("title").text().trim().replace(/\s\s+/g, ',').split(',')[0]; console.log("(2) | ",titleobj);}
                descobj = $('meta[property="og:description" i]').eq(0).attr('content');
                if (!descobj) {descobj = $("meta[name='description' i]").eq(0).attr("content");}
                imgobj = $('meta[property="og:image" i]').attr('content');

                // BUILD METADATA LIST
                metalist[site]={};
                if (sitelist[site]) (metalist[site].url=sitelist[site]);
                if (titleobj) (metalist[site].title=titleobj);
                if (descobj) (metalist[site].description=descobj);
                if (imgobj) (metalist[site].image=imgobj);
            } else {console.log("html body was empty")}


            progress--;
            if (progress===0) {
                // console.log(metalist);
                json = JSON.stringify(metalist,null,2);
                fs.writeFile('./data/metadataFromURLs.json', json, 'utf8', (err) => {  
                    if (err) throw err;
                    console.log('Metadata written to file');
                });
                 
                const fields = [];
                try {
                    // console.log(metalist)
                    // console.log("-------------------LOLOLOLOL-----------------")
                    const parser = new json2csv(fields);
                    const csv = utf8.encode(parser.parse(metalist));
                    // console.log(csv)
                    fs.writeFile('_scrapedURLs.csv', csv, 'utf8', (err) => {  
                        if (err) throw err;
                        console.log('CSV written to file');
                    });
                } catch (err) {
                  console.error(err);
                }
            };

            // console.log($("title").text().trim().replace(/\s\s+/g, ',').split(','));
            // console.log($("meta[name='description' i]").eq(0).attr("content"));

            // console.log($('meta[property="og:url"]').eq(0).attr('content'));
            // console.log($('meta[property="og:locale" i]').eq(0).attr('content'));
            // console.log($('meta[property="og:locale:alternate" i]').eq(0).attr('content'));
            // console.log($('meta[property="og:title" i]').eq(0).attr('content'));
            // console.log($('meta[property="og:type" i]').eq(0).attr('content'));
            // console.log($('meta[property="og:description" i]').eq(0).attr('content'));
            // console.log($('meta[property="og:determiner" i]').eq(0).attr('content'));
            // console.log($('meta[property="og:site_name" i]').eq(0).attr('content'));
            // console.log($('meta[property="og:image" i]').attr('content'));
            // console.log(metalist[sitelist[site]].title);
            console.log(chalk.red("------------------------------------------------------"));
            callback(metalist);
            // console.log($("meta[name='Viewport' i]").attr("content"));
            // console.log($("meta[name='Viewport' i]").attr("content"));
        }})(site));
    }
};

// crawl(function (result) {
//     global.test=result;
// });

// Start an IIFE to use `await` at the top level
(async function(){
    let json = await crawl(function (result) {
        global.test=result;
        // console.log(result);
    });
})();